syntax = "proto3";

option go_package = "github.com/trimble-oss/tierceron/atrium/vestibulum/hive/plugins/trcshtalk/trcshtalksdk";

package trcshtalksdk;

service TrcshTalkService {
    rpc Interact(InteractionRequest) returns (InteractionResponse);
}

message InteractionRequest {
    string message_id = 1;
    repeated Interactions interactions = 2;
    string query_id = 3;
    repeated string data = 4;
    repeated PluginQuery queries = 6;
}

message InteractionResponse {
    string message_id = 1;
    string results = 2;
}

enum Interactions {
    // if an interaction deprecates, comment it out
    // if adding an interaction, append to the end incrementing integer
    ALL = 0; // Default
    HEALTH_CHECK = 1;
    TRCDB = 2;
    VICO = 3;
    // future plugins
}

enum PluginQuery {
    ACTIVE_COUNT = 0;
}
