// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: praeviussdk/praeviussdk.proto

package praeviussdk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenericProxy_ForwardRequest_FullMethodName = "/praevioussdk.GenericProxy/ForwardRequest"
)

// GenericProxyClient is the client API for GenericProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenericProxyClient interface {
	ForwardRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
}

type genericProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewGenericProxyClient(cc grpc.ClientConnInterface) GenericProxyClient {
	return &genericProxyClient{cc}
}

func (c *genericProxyClient) ForwardRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, GenericProxy_ForwardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenericProxyServer is the server API for GenericProxy service.
// All implementations must embed UnimplementedGenericProxyServer
// for forward compatibility.
type GenericProxyServer interface {
	ForwardRequest(context.Context, *HttpRequest) (*HttpResponse, error)
	mustEmbedUnimplementedGenericProxyServer()
}

// UnimplementedGenericProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenericProxyServer struct{}

func (UnimplementedGenericProxyServer) ForwardRequest(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardRequest not implemented")
}
func (UnimplementedGenericProxyServer) mustEmbedUnimplementedGenericProxyServer() {}
func (UnimplementedGenericProxyServer) testEmbeddedByValue()                      {}

// UnsafeGenericProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenericProxyServer will
// result in compilation errors.
type UnsafeGenericProxyServer interface {
	mustEmbedUnimplementedGenericProxyServer()
}

func RegisterGenericProxyServer(s grpc.ServiceRegistrar, srv GenericProxyServer) {
	// If the following call pancis, it indicates UnimplementedGenericProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenericProxy_ServiceDesc, srv)
}

func _GenericProxy_ForwardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericProxyServer).ForwardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenericProxy_ForwardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericProxyServer).ForwardRequest(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenericProxy_ServiceDesc is the grpc.ServiceDesc for GenericProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenericProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "praevioussdk.GenericProxy",
	HandlerType: (*GenericProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardRequest",
			Handler:    _GenericProxy_ForwardRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "praeviussdk/praeviussdk.proto",
}
