# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pr:
  branches:
    include:
    - develop
    - main
    exclude:
    - releases/comprehensive/1.0.0

pool: 'TierceronPool'
resources:
  repositories:
  - repository: VaultConfig.Bootstrap
    type: git
    endpoint: AzureBuilderConnection
    name: Spectrum/_git/VaultConfig.Bootstrap
    ref: main
  - repository: VaultConfig.Test
    type: git
    endpoint: AzureBuilderConnection
    name: Spectrum/_git/VaultConfig.Test
    ref: main
  - repository: VaultConfig.TenantConfig
    type: git
    endpoint: AzureBuilderConnection
    name: Spectrum/_git/VaultConfig.TenantConfig
    ref: main
  - repository: tierceron-hat
    type: github
    endpoint: trimble-oss
    name: trimble-oss/tierceron-hat
    ref: main
  - repository: client-go
    type: github
    endpoint: trimble-oss
    name: trimble-oss/client-go
    ref: pathvisitor
  - repository: cli-runtime
    type: github
    endpoint: trimble-oss
    name: trimble-oss/cli-runtime
    ref: pathvisitor
  - repository: kubectl
    type: github
    endpoint: trimble-oss
    name: trimble-oss/kubectl
    ref: pathvisitor

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOPATH: '$(system.defaultWorkingDirectory)' # Go workspace path
  GOCACHE: '$(Pipeline.Workspace)/.cache/go-build/'
  GO_CACHE_DIR: $(Pipeline.Workspace)/.cache/go-build/
  modulePath: 'tierceron' # Path to the module's code

steps:
- task: GoTool@0
  inputs:
    version: '1.20.1'
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'
- checkout: VaultConfig.Bootstrap
- checkout: VaultConfig.TenantConfig
- checkout: VaultConfig.Test
- checkout: tierceron-hat
- checkout: client-go
- checkout: cli-runtime
- checkout: kubectl
- checkout: self
- task: Cache@2
  inputs:
    key: 'go | "$(Agent.OS)" | $(system.defaultWorkingDirectory)/$(modulePath)/go.mod'
    restoreKeys: | 
      go | "$(Agent.OS)"
    path: $(GO_CACHE_DIR)
  displayName: Cache GO packages
- script: |
    go version
    pwd
    echo $GOBIN
    echo "Compile start"

    echo "Compile Linux"
    GOBIN= CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOCACHE=$GOCACHE go install  -a -ldflags '-w' -tags "azure memonly tc" github.com/trimble-oss/tierceron/trcsh
    if [[ ! -f $GOBIN/trcsh ]] ; then
        echo File trcsh was not built, aborting.
        exit 1
    fi

    echo "Compile Agent plugin trc-vault-carrier-plugin"
    GOBIN= CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOCACHE=$GOCACHE go build  -tags "tc memonly awsecr insecure" -o $GOBIN/trc-vault-carrier-plugin github.com/trimble-oss/tierceron/trcvault/plugins/carrier
    if [[ ! -f $GOBIN/trc-vault-carrier-plugin ]] ; then
        echo File trc vault plugin was not built, aborting.
        exit 1
    fi

    echo "Compile Test Linux trc-vault-plugin"
    GOBIN= CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOCACHE=$GOCACHE go build  -tags "tc harbinger memonly" -o $GOBIN/trc-vault-plugin github.com/trimble-oss/tierceron/trcvault/plugins/trcdb
    if [[ ! -f $GOBIN/trc-vault-plugin ]] ; then
        echo File trc vault plugin was not built, aborting.
        exit 1
    fi

    echo "Compile Prod Linux trc-vault-plugin-prod"
    GOBIN= CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOCACHE=$GOCACHE go build  -tags "tc memonly prod" -o $GOBIN/trc-vault-plugin-prod github.com/trimble-oss/tierceron/trcvault/plugins/trcdb
    if [[ ! -f $GOBIN/trc-vault-plugin-prod ]] ; then
        echo File trc vault plugin was not built, aborting.
        exit 1
    fi

    sha256sum $GOBIN/trcsh | cut -d' ' -f1 > $GOBIN/trcsh.sha256
    sha256sum $GOBIN/trc-vault-carrier-plugin | cut -d' ' -f1 > $GOBIN/trc-vault-carrier-plugin.sha256
    sha256sum $GOBIN/trc-vault-plugin | cut -d' ' -f1 > $GOBIN/trc-vault-plugin.sha256
    sha256sum $GOBIN/trc-vault-plugin-prod | cut -d' ' -f1 > $GOBIN/trc-vault-plugin-prod.sha256

    echo "Compile Complete"
    cp $GOBIN/trcsh $(Build.ArtifactStagingDirectory)
    cp $GOBIN/trcsh.sha256 $(Build.ArtifactStagingDirectory)

    cp $GOBIN/trc-vault-carrier-plugin $(Build.ArtifactStagingDirectory)
    cp $GOBIN/trc-vault-carrier-plugin.sha256 $(Build.ArtifactStagingDirectory)
    cp $GOBIN/trc-vault-plugin  $(Build.ArtifactStagingDirectory)
    cp $GOBIN/trc-vault-plugin-prod  $(Build.ArtifactStagingDirectory)
    cp $GOBIN/trc-vault-plugin.sha256  $(Build.ArtifactStagingDirectory)
    cp $GOBIN/trc-vault-plugin-prod.sha256  $(Build.ArtifactStagingDirectory)
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Spectrum Snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: false
    testDirectory: '$(modulePath)'
    targetFile: go.mod
    projectName: 'Tierceron'
    organization: '3e7f6c88-f6ec-4436-8042-85455c5b39e8'
    additionalArguments: '-d'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
