# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
    - releases/legacy/1.0.0
    exclude:
    - main
    - develop

pool:
  vmImage: 'ubuntu-latest'
resources:
  repositories:
  - repository: VaultConfig.Bootstrap
    type: git
    endpoint: AzureBuilderConnection
    name: Spectrum/_git/VaultConfig.Bootstrap
    ref: develop
  - repository: VaultConfig.Test
    type: git
    endpoint: AzureBuilderConnection
    name: Spectrum/_git/VaultConfig.Test
    ref: develop
  - repository: VaultConfig.TenantConfig
    type: git
    endpoint: AzureBuilderConnection
    name: Spectrum/_git/VaultConfig.TenantConfig
    ref: develop

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOPATH: '$(system.defaultWorkingDirectory)' # Go workspace path
  modulePath: 'tierceron' # Path to the module's code

steps:
- task: GoTool@0
  inputs:
    version: '1.17.8'
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'
- checkout: VaultConfig.Bootstrap
- checkout: VaultConfig.TenantConfig
- checkout: VaultConfig.Test
- checkout: self
- script: |
    go version
    pwd
    echo $GOBIN
    echo "Mod download"
    go mod download
    echo "Compile start"

    for p in trcconfig trcpub trcinit trcinitp trcx trcxp trcsub; do
      echo Compiling $p
      GOOS=linux GOARCH=amd64 go install tierceron/$p
      if [[ ! -f $GOBIN/$p ]] ; then
          echo File $p was not built, aborting.
          exit 1
      fi
    done
  
    echo Compiling conflib
    GOOS=linux GOARCH=amd64 go build -buildmode=c-shared -o $GOBIN/nc.so tierceron/configlib
    if [[ ! -f $GOBIN/nc.so ]] ; then
        echo File nc.so was not built, aborting.
        exit 1
    fi

    echo "Compile Complete"
    cp $GOBIN/trcconfig $(Build.ArtifactStagingDirectory)/vaultconfig
    cp $GOBIN/trcpub $(Build.ArtifactStagingDirectory)/vaultpub
    cp $GOBIN/trcsub $(Build.ArtifactStagingDirectory)/vaultsub
    cp $GOBIN/trcinit $(Build.ArtifactStagingDirectory)/vaultinit
    cp $GOBIN/trcx $(Build.ArtifactStagingDirectory)/vaultx
    cp $GOBIN/nc.so $(Build.ArtifactStagingDirectory)
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: vaultconfig
    buildContext: '$(Build.ArtifactStagingDirectory)'
    command: build
    dockerfile: '**/docker/legacy/vaultconfig/Dockerfile'
    tags: |
      $(Build.SourceVersion)

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: vaultpub
    buildContext: '$(Build.ArtifactStagingDirectory)'
    command: build
    dockerfile: '**/docker/legacy/vaultpub/Dockerfile'
    tags: |
      $(Build.SourceVersion)

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'Seattle AWS Development'
    regionName: 'us-west-2'
    imageSource: 'imagename'
    sourceImageName: 'vaultconfig'
    sourceImageTag: '$(Build.SourceVersion)'
    repositoryName: 'vaultconfig'
    pushTag: '$(Build.SourceVersion)'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'Seattle AWS Development'
    regionName: 'us-west-2'
    imageSource: 'imagename'
    sourceImageName: 'vaultconfig'
    sourceImageTag: '$(Build.SourceVersion)'
    repositoryName: 'vaultconfig'
    pushTag: 'latest'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'Seattle AWS Development'
    regionName: 'us-west-2'
    imageSource: 'imagename'
    sourceImageName: 'vaultpub'
    sourceImageTag: '$(Build.SourceVersion)'
    repositoryName: 'vaultpub'
    pushTag: '$(Build.SourceVersion)'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'Seattle AWS Development'
    regionName: 'us-west-2'
    imageSource: 'imagename'
    sourceImageName: 'vaultpub'
    sourceImageTag: '$(Build.SourceVersion)'
    repositoryName: 'vaultpub'
    pushTag: 'latest'