// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: trcshtalksdk/trcshtalksdk.proto

package trcshtalksdk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrcshTalkService_RunDiagnostics_FullMethodName = "/trcshtalksdk.TrcshTalkService/RunDiagnostics"
)

// TrcshTalkServiceClient is the client API for TrcshTalkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrcshTalkServiceClient interface {
	RunDiagnostics(ctx context.Context, in *DiagnosticRequest, opts ...grpc.CallOption) (*DiagnosticResponse, error)
}

type trcshTalkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrcshTalkServiceClient(cc grpc.ClientConnInterface) TrcshTalkServiceClient {
	return &trcshTalkServiceClient{cc}
}

func (c *trcshTalkServiceClient) RunDiagnostics(ctx context.Context, in *DiagnosticRequest, opts ...grpc.CallOption) (*DiagnosticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticResponse)
	err := c.cc.Invoke(ctx, TrcshTalkService_RunDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrcshTalkServiceServer is the server API for TrcshTalkService service.
// All implementations must embed UnimplementedTrcshTalkServiceServer
// for forward compatibility.
type TrcshTalkServiceServer interface {
	RunDiagnostics(context.Context, *DiagnosticRequest) (*DiagnosticResponse, error)
	mustEmbedUnimplementedTrcshTalkServiceServer()
}

// UnimplementedTrcshTalkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrcshTalkServiceServer struct{}

func (UnimplementedTrcshTalkServiceServer) RunDiagnostics(context.Context, *DiagnosticRequest) (*DiagnosticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunDiagnostics not implemented")
}
func (UnimplementedTrcshTalkServiceServer) mustEmbedUnimplementedTrcshTalkServiceServer() {}
func (UnimplementedTrcshTalkServiceServer) testEmbeddedByValue()                          {}

// UnsafeTrcshTalkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrcshTalkServiceServer will
// result in compilation errors.
type UnsafeTrcshTalkServiceServer interface {
	mustEmbedUnimplementedTrcshTalkServiceServer()
}

func RegisterTrcshTalkServiceServer(s grpc.ServiceRegistrar, srv TrcshTalkServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrcshTalkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrcshTalkService_ServiceDesc, srv)
}

func _TrcshTalkService_RunDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrcshTalkServiceServer).RunDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrcshTalkService_RunDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrcshTalkServiceServer).RunDiagnostics(ctx, req.(*DiagnosticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrcshTalkService_ServiceDesc is the grpc.ServiceDesc for TrcshTalkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrcshTalkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trcshtalksdk.TrcshTalkService",
	HandlerType: (*TrcshTalkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunDiagnostics",
			Handler:    _TrcshTalkService_RunDiagnostics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trcshtalksdk/trcshtalksdk.proto",
}
