// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: trcshtalksdk/trcshtalksdk.proto

package trcshtalksdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interactions int32

const (
	// if an interaction deprecates, comment it out
	// if adding an interaction, append to the end incrementing integer
	Interactions_ALL          Interactions = 0 // Default
	Interactions_HEALTH_CHECK Interactions = 1
	Interactions_TRCDB        Interactions = 2
	Interactions_VICO         Interactions = 3 // future plugins
)

// Enum value maps for Interactions.
var (
	Interactions_name = map[int32]string{
		0: "ALL",
		1: "HEALTH_CHECK",
		2: "TRCDB",
		3: "VICO",
	}
	Interactions_value = map[string]int32{
		"ALL":          0,
		"HEALTH_CHECK": 1,
		"TRCDB":        2,
		"VICO":         3,
	}
)

func (x Interactions) Enum() *Interactions {
	p := new(Interactions)
	*p = x
	return p
}

func (x Interactions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interactions) Descriptor() protoreflect.EnumDescriptor {
	return file_trcshtalksdk_trcshtalksdk_proto_enumTypes[0].Descriptor()
}

func (Interactions) Type() protoreflect.EnumType {
	return &file_trcshtalksdk_trcshtalksdk_proto_enumTypes[0]
}

func (x Interactions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interactions.Descriptor instead.
func (Interactions) EnumDescriptor() ([]byte, []int) {
	return file_trcshtalksdk_trcshtalksdk_proto_rawDescGZIP(), []int{0}
}

type PluginQuery int32

const (
	PluginQuery_ACTIVE_COUNT PluginQuery = 0
)

// Enum value maps for PluginQuery.
var (
	PluginQuery_name = map[int32]string{
		0: "ACTIVE_COUNT",
	}
	PluginQuery_value = map[string]int32{
		"ACTIVE_COUNT": 0,
	}
)

func (x PluginQuery) Enum() *PluginQuery {
	p := new(PluginQuery)
	*p = x
	return p
}

func (x PluginQuery) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginQuery) Descriptor() protoreflect.EnumDescriptor {
	return file_trcshtalksdk_trcshtalksdk_proto_enumTypes[1].Descriptor()
}

func (PluginQuery) Type() protoreflect.EnumType {
	return &file_trcshtalksdk_trcshtalksdk_proto_enumTypes[1]
}

func (x PluginQuery) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginQuery.Descriptor instead.
func (PluginQuery) EnumDescriptor() ([]byte, []int) {
	return file_trcshtalksdk_trcshtalksdk_proto_rawDescGZIP(), []int{1}
}

type InteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Interactions  []Interactions         `protobuf:"varint,2,rep,packed,name=interactions,proto3,enum=trcshtalksdk.Interactions" json:"interactions,omitempty"`
	QueryId       string                 `protobuf:"bytes,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Data          []string               `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	Queries       []PluginQuery          `protobuf:"varint,6,rep,packed,name=queries,proto3,enum=trcshtalksdk.PluginQuery" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionRequest) Reset() {
	*x = InteractionRequest{}
	mi := &file_trcshtalksdk_trcshtalksdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionRequest) ProtoMessage() {}

func (x *InteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trcshtalksdk_trcshtalksdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionRequest.ProtoReflect.Descriptor instead.
func (*InteractionRequest) Descriptor() ([]byte, []int) {
	return file_trcshtalksdk_trcshtalksdk_proto_rawDescGZIP(), []int{0}
}

func (x *InteractionRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *InteractionRequest) GetInteractions() []Interactions {
	if x != nil {
		return x.Interactions
	}
	return nil
}

func (x *InteractionRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *InteractionRequest) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InteractionRequest) GetQueries() []PluginQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type InteractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Results       string                 `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionResponse) Reset() {
	*x = InteractionResponse{}
	mi := &file_trcshtalksdk_trcshtalksdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionResponse) ProtoMessage() {}

func (x *InteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trcshtalksdk_trcshtalksdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionResponse.ProtoReflect.Descriptor instead.
func (*InteractionResponse) Descriptor() ([]byte, []int) {
	return file_trcshtalksdk_trcshtalksdk_proto_rawDescGZIP(), []int{1}
}

func (x *InteractionResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *InteractionResponse) GetResults() string {
	if x != nil {
		return x.Results
	}
	return ""
}

var File_trcshtalksdk_trcshtalksdk_proto protoreflect.FileDescriptor

const file_trcshtalksdk_trcshtalksdk_proto_rawDesc = "" +
	"\n" +
	"\x1ftrcshtalksdk/trcshtalksdk.proto\x12\ftrcshtalksdk\"\xd7\x01\n" +
	"\x12InteractionRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12>\n" +
	"\finteractions\x18\x02 \x03(\x0e2\x1a.trcshtalksdk.InteractionsR\finteractions\x12\x19\n" +
	"\bquery_id\x18\x03 \x01(\tR\aqueryId\x12\x12\n" +
	"\x04data\x18\x04 \x03(\tR\x04data\x123\n" +
	"\aqueries\x18\x06 \x03(\x0e2\x19.trcshtalksdk.PluginQueryR\aqueries\"N\n" +
	"\x13InteractionResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\aresults\x18\x02 \x01(\tR\aresults*>\n" +
	"\fInteractions\x12\a\n" +
	"\x03ALL\x10\x00\x12\x10\n" +
	"\fHEALTH_CHECK\x10\x01\x12\t\n" +
	"\x05TRCDB\x10\x02\x12\b\n" +
	"\x04VICO\x10\x03*\x1f\n" +
	"\vPluginQuery\x12\x10\n" +
	"\fACTIVE_COUNT\x10\x002c\n" +
	"\x10TrcshTalkService\x12O\n" +
	"\bInteract\x12 .trcshtalksdk.InteractionRequest\x1a!.trcshtalksdk.InteractionResponseBXZVgithub.com/trimble-oss/tierceron/atrium/vestibulum/hive/plugins/trcshtalk/trcshtalksdkb\x06proto3"

var (
	file_trcshtalksdk_trcshtalksdk_proto_rawDescOnce sync.Once
	file_trcshtalksdk_trcshtalksdk_proto_rawDescData []byte
)

func file_trcshtalksdk_trcshtalksdk_proto_rawDescGZIP() []byte {
	file_trcshtalksdk_trcshtalksdk_proto_rawDescOnce.Do(func() {
		file_trcshtalksdk_trcshtalksdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trcshtalksdk_trcshtalksdk_proto_rawDesc), len(file_trcshtalksdk_trcshtalksdk_proto_rawDesc)))
	})
	return file_trcshtalksdk_trcshtalksdk_proto_rawDescData
}

var file_trcshtalksdk_trcshtalksdk_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_trcshtalksdk_trcshtalksdk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trcshtalksdk_trcshtalksdk_proto_goTypes = []any{
	(Interactions)(0),           // 0: trcshtalksdk.Interactions
	(PluginQuery)(0),            // 1: trcshtalksdk.PluginQuery
	(*InteractionRequest)(nil),  // 2: trcshtalksdk.InteractionRequest
	(*InteractionResponse)(nil), // 3: trcshtalksdk.InteractionResponse
}
var file_trcshtalksdk_trcshtalksdk_proto_depIdxs = []int32{
	0, // 0: trcshtalksdk.InteractionRequest.interactions:type_name -> trcshtalksdk.Interactions
	1, // 1: trcshtalksdk.InteractionRequest.queries:type_name -> trcshtalksdk.PluginQuery
	2, // 2: trcshtalksdk.TrcshTalkService.Interact:input_type -> trcshtalksdk.InteractionRequest
	3, // 3: trcshtalksdk.TrcshTalkService.Interact:output_type -> trcshtalksdk.InteractionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trcshtalksdk_trcshtalksdk_proto_init() }
func file_trcshtalksdk_trcshtalksdk_proto_init() {
	if File_trcshtalksdk_trcshtalksdk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trcshtalksdk_trcshtalksdk_proto_rawDesc), len(file_trcshtalksdk_trcshtalksdk_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trcshtalksdk_trcshtalksdk_proto_goTypes,
		DependencyIndexes: file_trcshtalksdk_trcshtalksdk_proto_depIdxs,
		EnumInfos:         file_trcshtalksdk_trcshtalksdk_proto_enumTypes,
		MessageInfos:      file_trcshtalksdk_trcshtalksdk_proto_msgTypes,
	}.Build()
	File_trcshtalksdk_trcshtalksdk_proto = out.File
	file_trcshtalksdk_trcshtalksdk_proto_goTypes = nil
	file_trcshtalksdk_trcshtalksdk_proto_depIdxs = nil
}
