name: trcUI
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.0.0<=3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_router: ^2.0.0-alpha+14
  angular_components: ^0.14.0-alpha


dev_dependencies:
  angular_test: ^2.0.0-alpha+11
  build_runner: ^1.5.0
  build_web_compilers: ">=1.2.0 <3.0.0"
  test: ^1.3.0
  build_daemon: ^1.0.0
  build_config: '>=0.4.0 < 0.4.1'
