// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package twirpapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request for retrieving a template file from the vault
type TemplateReq struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateReq) Reset()         { *m = TemplateReq{} }
func (m *TemplateReq) String() string { return proto.CompactTextString(m) }
func (*TemplateReq) ProtoMessage()    {}
func (*TemplateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a77e16b41b29f2a4, []int{0}
}
func (m *TemplateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateReq.Unmarshal(m, b)
}
func (m *TemplateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateReq.Marshal(b, m, deterministic)
}
func (dst *TemplateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateReq.Merge(dst, src)
}
func (m *TemplateReq) XXX_Size() int {
	return xxx_messageInfo_TemplateReq.Size(m)
}
func (m *TemplateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateReq.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateReq proto.InternalMessageInfo

func (m *TemplateReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *TemplateReq) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

// Response containing template and extension as stored in the vault
type TemplateResp struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Ext                  string   `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateResp) Reset()         { *m = TemplateResp{} }
func (m *TemplateResp) String() string { return proto.CompactTextString(m) }
func (*TemplateResp) ProtoMessage()    {}
func (*TemplateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a77e16b41b29f2a4, []int{1}
}
func (m *TemplateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateResp.Unmarshal(m, b)
}
func (m *TemplateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateResp.Marshal(b, m, deterministic)
}
func (dst *TemplateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateResp.Merge(dst, src)
}
func (m *TemplateResp) XXX_Size() int {
	return xxx_messageInfo_TemplateResp.Size(m)
}
func (m *TemplateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateResp.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateResp proto.InternalMessageInfo

func (m *TemplateResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TemplateResp) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

// Request for checking the validity of credentials for a service in a given environment
type ValidationReq struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Env                  string   `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationReq) Reset()         { *m = ValidationReq{} }
func (m *ValidationReq) String() string { return proto.CompactTextString(m) }
func (*ValidationReq) ProtoMessage()    {}
func (*ValidationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a77e16b41b29f2a4, []int{2}
}
func (m *ValidationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationReq.Unmarshal(m, b)
}
func (m *ValidationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationReq.Marshal(b, m, deterministic)
}
func (dst *ValidationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationReq.Merge(dst, src)
}
func (m *ValidationReq) XXX_Size() int {
	return xxx_messageInfo_ValidationReq.Size(m)
}
func (m *ValidationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationReq proto.InternalMessageInfo

func (m *ValidationReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ValidationReq) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

type ValidationResp struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationResp) Reset()         { *m = ValidationResp{} }
func (m *ValidationResp) String() string { return proto.CompactTextString(m) }
func (*ValidationResp) ProtoMessage()    {}
func (*ValidationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a77e16b41b29f2a4, []int{3}
}
func (m *ValidationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResp.Unmarshal(m, b)
}
func (m *ValidationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResp.Marshal(b, m, deterministic)
}
func (dst *ValidationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResp.Merge(dst, src)
}
func (m *ValidationResp) XXX_Size() int {
	return xxx_messageInfo_ValidationResp.Size(m)
}
func (m *ValidationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResp proto.InternalMessageInfo

func (m *ValidationResp) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func init() {
	proto.RegisterType((*TemplateReq)(nil), "bitbucket.com.dexterchaney.whoville.twirpapi.TemplateReq")
	proto.RegisterType((*TemplateResp)(nil), "bitbucket.com.dexterchaney.whoville.twirpapi.TemplateResp")
	proto.RegisterType((*ValidationReq)(nil), "bitbucket.com.dexterchaney.whoville.twirpapi.ValidationReq")
	proto.RegisterType((*ValidationResp)(nil), "bitbucket.com.dexterchaney.whoville.twirpapi.ValidationResp")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_a77e16b41b29f2a4) }

var fileDescriptor_service_a77e16b41b29f2a4 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x82, 0x20, 0x5c, 0x29, 0x42, 0x9e, 0xa2, 0x4e, 0x28, 0x13, 0x42, 0xc8, 0x03,
	0xb0, 0x40, 0x58, 0x60, 0x41, 0x6c, 0x28, 0xaa, 0x18, 0xd8, 0x9c, 0xe4, 0x50, 0x4f, 0xb8, 0xb1,
	0x89, 0x8f, 0xb4, 0xec, 0xf0, 0x23, 0xf8, 0xb7, 0xc8, 0x56, 0x02, 0x65, 0x41, 0x6a, 0xb6, 0x77,
	0x67, 0x7f, 0x67, 0xbf, 0xa7, 0x83, 0x89, 0xc3, 0xa6, 0xa5, 0x12, 0xa5, 0x6d, 0x0c, 0x1b, 0x71,
	0x5a, 0x10, 0x17, 0x6f, 0xe5, 0x0b, 0xb2, 0x2c, 0xcd, 0x42, 0x56, 0xb8, 0x62, 0x6c, 0xca, 0xb9,
	0xaa, 0xf1, 0x5d, 0x2e, 0xe7, 0xa6, 0x25, 0xad, 0x51, 0xf2, 0x92, 0x1a, 0xab, 0x2c, 0xa5, 0x19,
	0x8c, 0x67, 0xb8, 0xb0, 0x5a, 0x31, 0xe6, 0xf8, 0x2a, 0x12, 0xd8, 0xed, 0xa6, 0x25, 0xd1, 0x51,
	0x74, 0xbc, 0x97, 0xf7, 0xa5, 0x10, 0xb0, 0xfd, 0x4c, 0x1a, 0x93, 0x51, 0x68, 0x07, 0x9d, 0x5e,
	0xc0, 0xfe, 0x2f, 0xec, 0xac, 0xbf, 0x53, 0x29, 0x56, 0x1d, 0x1a, 0xb4, 0x38, 0x84, 0x2d, 0x5c,
	0x71, 0x87, 0x79, 0x99, 0x66, 0x30, 0x79, 0x54, 0x9a, 0x2a, 0xc5, 0x64, 0xea, 0xff, 0x1f, 0xf5,
	0x70, 0xdd, 0xfe, 0xc0, 0x75, 0x9b, 0x9e, 0xc0, 0xc1, 0x3a, 0xec, 0xac, 0xa7, 0xc9, 0x85, 0x5e,
	0xa0, 0xe3, 0xbc, 0x2f, 0xcf, 0xbe, 0x46, 0x10, 0xcf, 0xbc, 0xd1, 0x9b, 0x87, 0x7b, 0xf1, 0x11,
	0xc1, 0xf8, 0x0e, 0xb9, 0xff, 0xaf, 0xb8, 0x94, 0x9b, 0xe4, 0x24, 0xd7, 0x42, 0x9a, 0x5e, 0x0d,
	0x45, 0x9d, 0x15, 0x9f, 0x11, 0xc4, 0x9d, 0x01, 0x14, 0xd9, 0x66, 0x83, 0xfe, 0xa4, 0x36, 0xbd,
	0x1e, 0x0e, 0x3b, 0x7b, 0x0b, 0x4f, 0x71, 0x7f, 0x54, 0xec, 0x84, 0xc5, 0x39, 0xff, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xb6, 0x48, 0x7f, 0xf0, 0x49, 0x02, 0x00, 0x00,
}
