// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/apinator/service.proto

package apinator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NoParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoParams) Reset()         { *m = NoParams{} }
func (m *NoParams) String() string { return proto.CompactTextString(m) }
func (*NoParams) ProtoMessage()    {}
func (*NoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{0}
}
func (m *NoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoParams.Unmarshal(m, b)
}
func (m *NoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoParams.Marshal(b, m, deterministic)
}
func (dst *NoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoParams.Merge(dst, src)
}
func (m *NoParams) XXX_Size() int {
	return xxx_messageInfo_NoParams.Size(m)
}
func (m *NoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_NoParams.DiscardUnknown(m)
}

var xxx_messageInfo_NoParams proto.InternalMessageInfo

type ListReq struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{1}
}
func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (dst *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(dst, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type ListResp struct {
	Templates            []string `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResp) Reset()         { *m = ListResp{} }
func (m *ListResp) String() string { return proto.CompactTextString(m) }
func (*ListResp) ProtoMessage()    {}
func (*ListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{2}
}
func (m *ListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResp.Unmarshal(m, b)
}
func (m *ListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResp.Marshal(b, m, deterministic)
}
func (dst *ListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResp.Merge(dst, src)
}
func (m *ListResp) XXX_Size() int {
	return xxx_messageInfo_ListResp.Size(m)
}
func (m *ListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListResp proto.InternalMessageInfo

func (m *ListResp) GetTemplates() []string {
	if m != nil {
		return m.Templates
	}
	return nil
}

// Request for retrieving a template file from the vault
type TemplateReq struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateReq) Reset()         { *m = TemplateReq{} }
func (m *TemplateReq) String() string { return proto.CompactTextString(m) }
func (*TemplateReq) ProtoMessage()    {}
func (*TemplateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{3}
}
func (m *TemplateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateReq.Unmarshal(m, b)
}
func (m *TemplateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateReq.Marshal(b, m, deterministic)
}
func (dst *TemplateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateReq.Merge(dst, src)
}
func (m *TemplateReq) XXX_Size() int {
	return xxx_messageInfo_TemplateReq.Size(m)
}
func (m *TemplateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateReq.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateReq proto.InternalMessageInfo

func (m *TemplateReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *TemplateReq) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

// Response containing template and extension as stored in the vault
type TemplateResp struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Ext                  string   `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateResp) Reset()         { *m = TemplateResp{} }
func (m *TemplateResp) String() string { return proto.CompactTextString(m) }
func (*TemplateResp) ProtoMessage()    {}
func (*TemplateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{4}
}
func (m *TemplateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateResp.Unmarshal(m, b)
}
func (m *TemplateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateResp.Marshal(b, m, deterministic)
}
func (dst *TemplateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateResp.Merge(dst, src)
}
func (m *TemplateResp) XXX_Size() int {
	return xxx_messageInfo_TemplateResp.Size(m)
}
func (m *TemplateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateResp.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateResp proto.InternalMessageInfo

func (m *TemplateResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TemplateResp) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

// Request for checking the validity of credentials for a service in a given environment
type ValidationReq struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Env                  string   `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationReq) Reset()         { *m = ValidationReq{} }
func (m *ValidationReq) String() string { return proto.CompactTextString(m) }
func (*ValidationReq) ProtoMessage()    {}
func (*ValidationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{5}
}
func (m *ValidationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationReq.Unmarshal(m, b)
}
func (m *ValidationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationReq.Marshal(b, m, deterministic)
}
func (dst *ValidationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationReq.Merge(dst, src)
}
func (m *ValidationReq) XXX_Size() int {
	return xxx_messageInfo_ValidationReq.Size(m)
}
func (m *ValidationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationReq proto.InternalMessageInfo

func (m *ValidationReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ValidationReq) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

type ValidationResp struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationResp) Reset()         { *m = ValidationResp{} }
func (m *ValidationResp) String() string { return proto.CompactTextString(m) }
func (*ValidationResp) ProtoMessage()    {}
func (*ValidationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{6}
}
func (m *ValidationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResp.Unmarshal(m, b)
}
func (m *ValidationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResp.Marshal(b, m, deterministic)
}
func (dst *ValidationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResp.Merge(dst, src)
}
func (m *ValidationResp) XXX_Size() int {
	return xxx_messageInfo_ValidationResp.Size(m)
}
func (m *ValidationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResp proto.InternalMessageInfo

func (m *ValidationResp) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

// Request for checking the validity of credentials for a service in a given environment
type ValuesRes struct {
	Envs                 []*ValuesRes_Env `protobuf:"bytes,2,rep,name=envs,proto3" json:"envs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ValuesRes) Reset()         { *m = ValuesRes{} }
func (m *ValuesRes) String() string { return proto.CompactTextString(m) }
func (*ValuesRes) ProtoMessage()    {}
func (*ValuesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{7}
}
func (m *ValuesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValuesRes.Unmarshal(m, b)
}
func (m *ValuesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValuesRes.Marshal(b, m, deterministic)
}
func (dst *ValuesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuesRes.Merge(dst, src)
}
func (m *ValuesRes) XXX_Size() int {
	return xxx_messageInfo_ValuesRes.Size(m)
}
func (m *ValuesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuesRes.DiscardUnknown(m)
}

var xxx_messageInfo_ValuesRes proto.InternalMessageInfo

func (m *ValuesRes) GetEnvs() []*ValuesRes_Env {
	if m != nil {
		return m.Envs
	}
	return nil
}

type ValuesRes_Env struct {
	Name                 string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Services             []*ValuesRes_Env_Service `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ValuesRes_Env) Reset()         { *m = ValuesRes_Env{} }
func (m *ValuesRes_Env) String() string { return proto.CompactTextString(m) }
func (*ValuesRes_Env) ProtoMessage()    {}
func (*ValuesRes_Env) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{7, 0}
}
func (m *ValuesRes_Env) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValuesRes_Env.Unmarshal(m, b)
}
func (m *ValuesRes_Env) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValuesRes_Env.Marshal(b, m, deterministic)
}
func (dst *ValuesRes_Env) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuesRes_Env.Merge(dst, src)
}
func (m *ValuesRes_Env) XXX_Size() int {
	return xxx_messageInfo_ValuesRes_Env.Size(m)
}
func (m *ValuesRes_Env) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuesRes_Env.DiscardUnknown(m)
}

var xxx_messageInfo_ValuesRes_Env proto.InternalMessageInfo

func (m *ValuesRes_Env) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ValuesRes_Env) GetServices() []*ValuesRes_Env_Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type ValuesRes_Env_Service struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Files                []*ValuesRes_Env_Service_File `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ValuesRes_Env_Service) Reset()         { *m = ValuesRes_Env_Service{} }
func (m *ValuesRes_Env_Service) String() string { return proto.CompactTextString(m) }
func (*ValuesRes_Env_Service) ProtoMessage()    {}
func (*ValuesRes_Env_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{7, 0, 0}
}
func (m *ValuesRes_Env_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValuesRes_Env_Service.Unmarshal(m, b)
}
func (m *ValuesRes_Env_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValuesRes_Env_Service.Marshal(b, m, deterministic)
}
func (dst *ValuesRes_Env_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuesRes_Env_Service.Merge(dst, src)
}
func (m *ValuesRes_Env_Service) XXX_Size() int {
	return xxx_messageInfo_ValuesRes_Env_Service.Size(m)
}
func (m *ValuesRes_Env_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuesRes_Env_Service.DiscardUnknown(m)
}

var xxx_messageInfo_ValuesRes_Env_Service proto.InternalMessageInfo

func (m *ValuesRes_Env_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ValuesRes_Env_Service) GetFiles() []*ValuesRes_Env_Service_File {
	if m != nil {
		return m.Files
	}
	return nil
}

type ValuesRes_Env_Service_File struct {
	Name                 string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*ValuesRes_Env_Service_File_Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ValuesRes_Env_Service_File) Reset()         { *m = ValuesRes_Env_Service_File{} }
func (m *ValuesRes_Env_Service_File) String() string { return proto.CompactTextString(m) }
func (*ValuesRes_Env_Service_File) ProtoMessage()    {}
func (*ValuesRes_Env_Service_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{7, 0, 0, 0}
}
func (m *ValuesRes_Env_Service_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValuesRes_Env_Service_File.Unmarshal(m, b)
}
func (m *ValuesRes_Env_Service_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValuesRes_Env_Service_File.Marshal(b, m, deterministic)
}
func (dst *ValuesRes_Env_Service_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuesRes_Env_Service_File.Merge(dst, src)
}
func (m *ValuesRes_Env_Service_File) XXX_Size() int {
	return xxx_messageInfo_ValuesRes_Env_Service_File.Size(m)
}
func (m *ValuesRes_Env_Service_File) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuesRes_Env_Service_File.DiscardUnknown(m)
}

var xxx_messageInfo_ValuesRes_Env_Service_File proto.InternalMessageInfo

func (m *ValuesRes_Env_Service_File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ValuesRes_Env_Service_File) GetValues() []*ValuesRes_Env_Service_File_Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type ValuesRes_Env_Service_File_Value struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValuesRes_Env_Service_File_Value) Reset()         { *m = ValuesRes_Env_Service_File_Value{} }
func (m *ValuesRes_Env_Service_File_Value) String() string { return proto.CompactTextString(m) }
func (*ValuesRes_Env_Service_File_Value) ProtoMessage()    {}
func (*ValuesRes_Env_Service_File_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{7, 0, 0, 0, 0}
}
func (m *ValuesRes_Env_Service_File_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValuesRes_Env_Service_File_Value.Unmarshal(m, b)
}
func (m *ValuesRes_Env_Service_File_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValuesRes_Env_Service_File_Value.Marshal(b, m, deterministic)
}
func (dst *ValuesRes_Env_Service_File_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuesRes_Env_Service_File_Value.Merge(dst, src)
}
func (m *ValuesRes_Env_Service_File_Value) XXX_Size() int {
	return xxx_messageInfo_ValuesRes_Env_Service_File_Value.Size(m)
}
func (m *ValuesRes_Env_Service_File_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuesRes_Env_Service_File_Value.DiscardUnknown(m)
}

var xxx_messageInfo_ValuesRes_Env_Service_File_Value proto.InternalMessageInfo

func (m *ValuesRes_Env_Service_File_Value) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ValuesRes_Env_Service_File_Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ValuesRes_Env_Service_File_Value) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type GetValuesReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValuesReq) Reset()         { *m = GetValuesReq{} }
func (m *GetValuesReq) String() string { return proto.CompactTextString(m) }
func (*GetValuesReq) ProtoMessage()    {}
func (*GetValuesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{8}
}
func (m *GetValuesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValuesReq.Unmarshal(m, b)
}
func (m *GetValuesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValuesReq.Marshal(b, m, deterministic)
}
func (dst *GetValuesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValuesReq.Merge(dst, src)
}
func (m *GetValuesReq) XXX_Size() int {
	return xxx_messageInfo_GetValuesReq.Size(m)
}
func (m *GetValuesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValuesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetValuesReq proto.InternalMessageInfo

// ///////////////////////////////////////////////////////
// Initialization Messages                             //
// ///////////////////////////////////////////////////////
type InitReq struct {
	Files                []*InitReq_SeedFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Username             string              `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string              `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InitReq) Reset()         { *m = InitReq{} }
func (m *InitReq) String() string { return proto.CompactTextString(m) }
func (*InitReq) ProtoMessage()    {}
func (*InitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{9}
}
func (m *InitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReq.Unmarshal(m, b)
}
func (m *InitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReq.Marshal(b, m, deterministic)
}
func (dst *InitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReq.Merge(dst, src)
}
func (m *InitReq) XXX_Size() int {
	return xxx_messageInfo_InitReq.Size(m)
}
func (m *InitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReq.DiscardUnknown(m)
}

var xxx_messageInfo_InitReq proto.InternalMessageInfo

func (m *InitReq) GetFiles() []*InitReq_SeedFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *InitReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InitReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type InitReq_SeedFile struct {
	Env                  string   `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitReq_SeedFile) Reset()         { *m = InitReq_SeedFile{} }
func (m *InitReq_SeedFile) String() string { return proto.CompactTextString(m) }
func (*InitReq_SeedFile) ProtoMessage()    {}
func (*InitReq_SeedFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{9, 0}
}
func (m *InitReq_SeedFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReq_SeedFile.Unmarshal(m, b)
}
func (m *InitReq_SeedFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReq_SeedFile.Marshal(b, m, deterministic)
}
func (dst *InitReq_SeedFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReq_SeedFile.Merge(dst, src)
}
func (m *InitReq_SeedFile) XXX_Size() int {
	return xxx_messageInfo_InitReq_SeedFile.Size(m)
}
func (m *InitReq_SeedFile) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReq_SeedFile.DiscardUnknown(m)
}

var xxx_messageInfo_InitReq_SeedFile proto.InternalMessageInfo

func (m *InitReq_SeedFile) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *InitReq_SeedFile) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type InitResp struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Logfile              string            `protobuf:"bytes,2,opt,name=logfile,proto3" json:"logfile,omitempty"`
	Tokens               []*InitResp_Token `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitResp) Reset()         { *m = InitResp{} }
func (m *InitResp) String() string { return proto.CompactTextString(m) }
func (*InitResp) ProtoMessage()    {}
func (*InitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{10}
}
func (m *InitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResp.Unmarshal(m, b)
}
func (m *InitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResp.Marshal(b, m, deterministic)
}
func (dst *InitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResp.Merge(dst, src)
}
func (m *InitResp) XXX_Size() int {
	return xxx_messageInfo_InitResp.Size(m)
}
func (m *InitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResp.DiscardUnknown(m)
}

var xxx_messageInfo_InitResp proto.InternalMessageInfo

func (m *InitResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *InitResp) GetLogfile() string {
	if m != nil {
		return m.Logfile
	}
	return ""
}

func (m *InitResp) GetTokens() []*InitResp_Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type InitResp_Token struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResp_Token) Reset()         { *m = InitResp_Token{} }
func (m *InitResp_Token) String() string { return proto.CompactTextString(m) }
func (*InitResp_Token) ProtoMessage()    {}
func (*InitResp_Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{10, 0}
}
func (m *InitResp_Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResp_Token.Unmarshal(m, b)
}
func (m *InitResp_Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResp_Token.Marshal(b, m, deterministic)
}
func (dst *InitResp_Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResp_Token.Merge(dst, src)
}
func (m *InitResp_Token) XXX_Size() int {
	return xxx_messageInfo_InitResp_Token.Size(m)
}
func (m *InitResp_Token) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResp_Token.DiscardUnknown(m)
}

var xxx_messageInfo_InitResp_Token proto.InternalMessageInfo

func (m *InitResp_Token) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InitResp_Token) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// ///////////////////////////////////////////////////////
// Web App LogIn Messages                              //
// ///////////////////////////////////////////////////////
type VaultStatus struct {
	Initialized          bool     `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	Sealed               bool     `protobuf:"varint,2,opt,name=sealed,proto3" json:"sealed,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VaultStatus) Reset()         { *m = VaultStatus{} }
func (m *VaultStatus) String() string { return proto.CompactTextString(m) }
func (*VaultStatus) ProtoMessage()    {}
func (*VaultStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{11}
}
func (m *VaultStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VaultStatus.Unmarshal(m, b)
}
func (m *VaultStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VaultStatus.Marshal(b, m, deterministic)
}
func (dst *VaultStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultStatus.Merge(dst, src)
}
func (m *VaultStatus) XXX_Size() int {
	return xxx_messageInfo_VaultStatus.Size(m)
}
func (m *VaultStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VaultStatus proto.InternalMessageInfo

func (m *VaultStatus) GetInitialized() bool {
	if m != nil {
		return m.Initialized
	}
	return false
}

func (m *VaultStatus) GetSealed() bool {
	if m != nil {
		return m.Sealed
	}
	return false
}

func (m *VaultStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{12}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AuthToken            string   `protobuf:"bytes,2,opt,name=authToken,proto3" json:"authToken,omitempty"`
	Errors               []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{13}
}
func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (dst *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(dst, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResp) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *LoginResp) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type UnsealReq struct {
	UnsealKey            string   `protobuf:"bytes,1,opt,name=unsealKey,proto3" json:"unsealKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsealReq) Reset()         { *m = UnsealReq{} }
func (m *UnsealReq) String() string { return proto.CompactTextString(m) }
func (*UnsealReq) ProtoMessage()    {}
func (*UnsealReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{14}
}
func (m *UnsealReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsealReq.Unmarshal(m, b)
}
func (m *UnsealReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsealReq.Marshal(b, m, deterministic)
}
func (dst *UnsealReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsealReq.Merge(dst, src)
}
func (m *UnsealReq) XXX_Size() int {
	return xxx_messageInfo_UnsealReq.Size(m)
}
func (m *UnsealReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsealReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnsealReq proto.InternalMessageInfo

func (m *UnsealReq) GetUnsealKey() string {
	if m != nil {
		return m.UnsealKey
	}
	return ""
}

type UnsealResp struct {
	Sealed               bool     `protobuf:"varint,1,opt,name=sealed,proto3" json:"sealed,omitempty"`
	Progress             int32    `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Needed               int32    `protobuf:"varint,3,opt,name=needed,proto3" json:"needed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsealResp) Reset()         { *m = UnsealResp{} }
func (m *UnsealResp) String() string { return proto.CompactTextString(m) }
func (*UnsealResp) ProtoMessage()    {}
func (*UnsealResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{15}
}
func (m *UnsealResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsealResp.Unmarshal(m, b)
}
func (m *UnsealResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsealResp.Marshal(b, m, deterministic)
}
func (dst *UnsealResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsealResp.Merge(dst, src)
}
func (m *UnsealResp) XXX_Size() int {
	return xxx_messageInfo_UnsealResp.Size(m)
}
func (m *UnsealResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsealResp.DiscardUnknown(m)
}

var xxx_messageInfo_UnsealResp proto.InternalMessageInfo

func (m *UnsealResp) GetSealed() bool {
	if m != nil {
		return m.Sealed
	}
	return false
}

func (m *UnsealResp) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *UnsealResp) GetNeeded() int32 {
	if m != nil {
		return m.Needed
	}
	return 0
}

// ///////////////////////////////////////////////////////
// GraphQL Messages                                    //
// ///////////////////////////////////////////////////////
type GraphQLQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphQLQuery) Reset()         { *m = GraphQLQuery{} }
func (m *GraphQLQuery) String() string { return proto.CompactTextString(m) }
func (*GraphQLQuery) ProtoMessage()    {}
func (*GraphQLQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{16}
}
func (m *GraphQLQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLQuery.Unmarshal(m, b)
}
func (m *GraphQLQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLQuery.Marshal(b, m, deterministic)
}
func (dst *GraphQLQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLQuery.Merge(dst, src)
}
func (m *GraphQLQuery) XXX_Size() int {
	return xxx_messageInfo_GraphQLQuery.Size(m)
}
func (m *GraphQLQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLQuery proto.InternalMessageInfo

func (m *GraphQLQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type GQLError struct {
	Message              string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Locations            []*GQLError_Location `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GQLError) Reset()         { *m = GQLError{} }
func (m *GQLError) String() string { return proto.CompactTextString(m) }
func (*GQLError) ProtoMessage()    {}
func (*GQLError) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{17}
}
func (m *GQLError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GQLError.Unmarshal(m, b)
}
func (m *GQLError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GQLError.Marshal(b, m, deterministic)
}
func (dst *GQLError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GQLError.Merge(dst, src)
}
func (m *GQLError) XXX_Size() int {
	return xxx_messageInfo_GQLError.Size(m)
}
func (m *GQLError) XXX_DiscardUnknown() {
	xxx_messageInfo_GQLError.DiscardUnknown(m)
}

var xxx_messageInfo_GQLError proto.InternalMessageInfo

func (m *GQLError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GQLError) GetLocations() []*GQLError_Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

type GQLError_Location struct {
	Line                 int32    `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column               int32    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GQLError_Location) Reset()         { *m = GQLError_Location{} }
func (m *GQLError_Location) String() string { return proto.CompactTextString(m) }
func (*GQLError_Location) ProtoMessage()    {}
func (*GQLError_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{17, 0}
}
func (m *GQLError_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GQLError_Location.Unmarshal(m, b)
}
func (m *GQLError_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GQLError_Location.Marshal(b, m, deterministic)
}
func (dst *GQLError_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GQLError_Location.Merge(dst, src)
}
func (m *GQLError_Location) XXX_Size() int {
	return xxx_messageInfo_GQLError_Location.Size(m)
}
func (m *GQLError_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_GQLError_Location.DiscardUnknown(m)
}

var xxx_messageInfo_GQLError_Location proto.InternalMessageInfo

func (m *GQLError_Location) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *GQLError_Location) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type GraphQLResp struct {
	Data                 *ValuesRes  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Errors               []*GQLError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GraphQLResp) Reset()         { *m = GraphQLResp{} }
func (m *GraphQLResp) String() string { return proto.CompactTextString(m) }
func (*GraphQLResp) ProtoMessage()    {}
func (*GraphQLResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{18}
}
func (m *GraphQLResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLResp.Unmarshal(m, b)
}
func (m *GraphQLResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLResp.Marshal(b, m, deterministic)
}
func (dst *GraphQLResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLResp.Merge(dst, src)
}
func (m *GraphQLResp) XXX_Size() int {
	return xxx_messageInfo_GraphQLResp.Size(m)
}
func (m *GraphQLResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLResp.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLResp proto.InternalMessageInfo

func (m *GraphQLResp) GetData() *ValuesRes {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GraphQLResp) GetErrors() []*GQLError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type TemplateData struct {
	Services             []*TemplateData_Service `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TemplateData) Reset()         { *m = TemplateData{} }
func (m *TemplateData) String() string { return proto.CompactTextString(m) }
func (*TemplateData) ProtoMessage()    {}
func (*TemplateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{19}
}
func (m *TemplateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateData.Unmarshal(m, b)
}
func (m *TemplateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateData.Marshal(b, m, deterministic)
}
func (dst *TemplateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateData.Merge(dst, src)
}
func (m *TemplateData) XXX_Size() int {
	return xxx_messageInfo_TemplateData.Size(m)
}
func (m *TemplateData) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateData.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateData proto.InternalMessageInfo

func (m *TemplateData) GetServices() []*TemplateData_Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type TemplateData_Service struct {
	Name                 string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Files                []*TemplateData_Service_File `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TemplateData_Service) Reset()         { *m = TemplateData_Service{} }
func (m *TemplateData_Service) String() string { return proto.CompactTextString(m) }
func (*TemplateData_Service) ProtoMessage()    {}
func (*TemplateData_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{19, 0}
}
func (m *TemplateData_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateData_Service.Unmarshal(m, b)
}
func (m *TemplateData_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateData_Service.Marshal(b, m, deterministic)
}
func (dst *TemplateData_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateData_Service.Merge(dst, src)
}
func (m *TemplateData_Service) XXX_Size() int {
	return xxx_messageInfo_TemplateData_Service.Size(m)
}
func (m *TemplateData_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateData_Service.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateData_Service proto.InternalMessageInfo

func (m *TemplateData_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TemplateData_Service) GetFiles() []*TemplateData_Service_File {
	if m != nil {
		return m.Files
	}
	return nil
}

type TemplateData_Service_File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Secrets              []string `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateData_Service_File) Reset()         { *m = TemplateData_Service_File{} }
func (m *TemplateData_Service_File) String() string { return proto.CompactTextString(m) }
func (*TemplateData_Service_File) ProtoMessage()    {}
func (*TemplateData_Service_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{19, 0, 0}
}
func (m *TemplateData_Service_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateData_Service_File.Unmarshal(m, b)
}
func (m *TemplateData_Service_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateData_Service_File.Marshal(b, m, deterministic)
}
func (dst *TemplateData_Service_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateData_Service_File.Merge(dst, src)
}
func (m *TemplateData_Service_File) XXX_Size() int {
	return xxx_messageInfo_TemplateData_Service_File.Size(m)
}
func (m *TemplateData_Service_File) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateData_Service_File.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateData_Service_File proto.InternalMessageInfo

func (m *TemplateData_Service_File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TemplateData_Service_File) GetSecrets() []string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type GQLTemplateResp struct {
	Data                 *TemplateData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Errors               []*GQLError   `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GQLTemplateResp) Reset()         { *m = GQLTemplateResp{} }
func (m *GQLTemplateResp) String() string { return proto.CompactTextString(m) }
func (*GQLTemplateResp) ProtoMessage()    {}
func (*GQLTemplateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{20}
}
func (m *GQLTemplateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GQLTemplateResp.Unmarshal(m, b)
}
func (m *GQLTemplateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GQLTemplateResp.Marshal(b, m, deterministic)
}
func (dst *GQLTemplateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GQLTemplateResp.Merge(dst, src)
}
func (m *GQLTemplateResp) XXX_Size() int {
	return xxx_messageInfo_GQLTemplateResp.Size(m)
}
func (m *GQLTemplateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GQLTemplateResp.DiscardUnknown(m)
}

var xxx_messageInfo_GQLTemplateResp proto.InternalMessageInfo

func (m *GQLTemplateResp) GetData() *TemplateData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GQLTemplateResp) GetErrors() []*GQLError {
	if m != nil {
		return m.Errors
	}
	return nil
}

// ///////////////////////////////////////////////////////
// Update API Messages                                    //
// ///////////////////////////////////////////////////////
type UpdateAPIReq struct {
	Urls                 []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAPIReq) Reset()         { *m = UpdateAPIReq{} }
func (m *UpdateAPIReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAPIReq) ProtoMessage()    {}
func (*UpdateAPIReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{21}
}
func (m *UpdateAPIReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAPIReq.Unmarshal(m, b)
}
func (m *UpdateAPIReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAPIReq.Marshal(b, m, deterministic)
}
func (dst *UpdateAPIReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAPIReq.Merge(dst, src)
}
func (m *UpdateAPIReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAPIReq.Size(m)
}
func (m *UpdateAPIReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAPIReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAPIReq proto.InternalMessageInfo

func (m *UpdateAPIReq) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

type UpdateAPIResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAPIResp) Reset()         { *m = UpdateAPIResp{} }
func (m *UpdateAPIResp) String() string { return proto.CompactTextString(m) }
func (*UpdateAPIResp) ProtoMessage()    {}
func (*UpdateAPIResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ab2afd909c3e7b43, []int{22}
}
func (m *UpdateAPIResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAPIResp.Unmarshal(m, b)
}
func (m *UpdateAPIResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAPIResp.Marshal(b, m, deterministic)
}
func (dst *UpdateAPIResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAPIResp.Merge(dst, src)
}
func (m *UpdateAPIResp) XXX_Size() int {
	return xxx_messageInfo_UpdateAPIResp.Size(m)
}
func (m *UpdateAPIResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAPIResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAPIResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NoParams)(nil), "viewpoint.whoville.apinator.NoParams")
	proto.RegisterType((*ListReq)(nil), "viewpoint.whoville.apinator.ListReq")
	proto.RegisterType((*ListResp)(nil), "viewpoint.whoville.apinator.ListResp")
	proto.RegisterType((*TemplateReq)(nil), "viewpoint.whoville.apinator.TemplateReq")
	proto.RegisterType((*TemplateResp)(nil), "viewpoint.whoville.apinator.TemplateResp")
	proto.RegisterType((*ValidationReq)(nil), "viewpoint.whoville.apinator.ValidationReq")
	proto.RegisterType((*ValidationResp)(nil), "viewpoint.whoville.apinator.ValidationResp")
	proto.RegisterType((*ValuesRes)(nil), "viewpoint.whoville.apinator.ValuesRes")
	proto.RegisterType((*ValuesRes_Env)(nil), "viewpoint.whoville.apinator.ValuesRes.Env")
	proto.RegisterType((*ValuesRes_Env_Service)(nil), "viewpoint.whoville.apinator.ValuesRes.Env.Service")
	proto.RegisterType((*ValuesRes_Env_Service_File)(nil), "viewpoint.whoville.apinator.ValuesRes.Env.Service.File")
	proto.RegisterType((*ValuesRes_Env_Service_File_Value)(nil), "viewpoint.whoville.apinator.ValuesRes.Env.Service.File.Value")
	proto.RegisterType((*GetValuesReq)(nil), "viewpoint.whoville.apinator.GetValuesReq")
	proto.RegisterType((*InitReq)(nil), "viewpoint.whoville.apinator.InitReq")
	proto.RegisterType((*InitReq_SeedFile)(nil), "viewpoint.whoville.apinator.InitReq.SeedFile")
	proto.RegisterType((*InitResp)(nil), "viewpoint.whoville.apinator.InitResp")
	proto.RegisterType((*InitResp_Token)(nil), "viewpoint.whoville.apinator.InitResp.Token")
	proto.RegisterType((*VaultStatus)(nil), "viewpoint.whoville.apinator.VaultStatus")
	proto.RegisterType((*LoginReq)(nil), "viewpoint.whoville.apinator.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "viewpoint.whoville.apinator.LoginResp")
	proto.RegisterType((*UnsealReq)(nil), "viewpoint.whoville.apinator.UnsealReq")
	proto.RegisterType((*UnsealResp)(nil), "viewpoint.whoville.apinator.UnsealResp")
	proto.RegisterType((*GraphQLQuery)(nil), "viewpoint.whoville.apinator.GraphQLQuery")
	proto.RegisterType((*GQLError)(nil), "viewpoint.whoville.apinator.GQLError")
	proto.RegisterType((*GQLError_Location)(nil), "viewpoint.whoville.apinator.GQLError.Location")
	proto.RegisterType((*GraphQLResp)(nil), "viewpoint.whoville.apinator.GraphQLResp")
	proto.RegisterType((*TemplateData)(nil), "viewpoint.whoville.apinator.TemplateData")
	proto.RegisterType((*TemplateData_Service)(nil), "viewpoint.whoville.apinator.TemplateData.Service")
	proto.RegisterType((*TemplateData_Service_File)(nil), "viewpoint.whoville.apinator.TemplateData.Service.File")
	proto.RegisterType((*GQLTemplateResp)(nil), "viewpoint.whoville.apinator.GQLTemplateResp")
	proto.RegisterType((*UpdateAPIReq)(nil), "viewpoint.whoville.apinator.UpdateAPIReq")
	proto.RegisterType((*UpdateAPIResp)(nil), "viewpoint.whoville.apinator.UpdateAPIResp")
}

func init() { proto.RegisterFile("rpc/apinator/service.proto", fileDescriptor_service_ab2afd909c3e7b43) }

var fileDescriptor_service_ab2afd909c3e7b43 = []byte{
	// 1095 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4f, 0x6f, 0xdc, 0x44,
	0x1b, 0x97, 0x77, 0xb3, 0x59, 0xfb, 0xd9, 0xb4, 0x7d, 0x35, 0xaa, 0x5e, 0x56, 0x26, 0x87, 0x68,
	0x68, 0x61, 0x93, 0x0a, 0x97, 0x86, 0xaa, 0x48, 0x54, 0x41, 0x6a, 0x4a, 0x58, 0x45, 0x6c, 0xab,
	0xc4, 0x69, 0xa2, 0x16, 0x10, 0xd2, 0x64, 0x77, 0x48, 0x46, 0xf1, 0xda, 0xce, 0xcc, 0xd8, 0x01,
	0x6e, 0xdc, 0xb8, 0x71, 0xe2, 0x03, 0x70, 0x84, 0x0f, 0x80, 0x10, 0xdf, 0x84, 0x33, 0x5f, 0x04,
	0xcd, 0x78, 0xc6, 0xf6, 0xaa, 0x91, 0xd7, 0x45, 0xdc, 0xe6, 0x37, 0x9e, 0xe7, 0xff, 0x3c, 0xcf,
	0x6f, 0x0c, 0x3e, 0x4f, 0xa7, 0xf7, 0x49, 0xca, 0x62, 0x22, 0x13, 0x7e, 0x5f, 0x50, 0x9e, 0xb3,
	0x29, 0x0d, 0x52, 0x9e, 0xc8, 0x04, 0xbd, 0x9d, 0x33, 0x7a, 0x95, 0x26, 0x2c, 0x96, 0xc1, 0xd5,
	0x79, 0x92, 0xb3, 0x28, 0xa2, 0x81, 0x3d, 0x8a, 0x01, 0xdc, 0xe7, 0xc9, 0x01, 0xe1, 0x64, 0x2e,
	0xf0, 0x3b, 0xd0, 0x9f, 0x30, 0x21, 0x43, 0x7a, 0x89, 0x86, 0xd0, 0x37, 0x4a, 0x86, 0xce, 0x86,
	0x33, 0xf2, 0x42, 0x0b, 0xf1, 0x08, 0xdc, 0xe2, 0x90, 0x48, 0xd1, 0x3a, 0x78, 0x92, 0xce, 0xd3,
	0x88, 0x48, 0x2a, 0x86, 0xce, 0x46, 0x77, 0xe4, 0x85, 0xd5, 0x06, 0x7e, 0x0c, 0x83, 0x17, 0x06,
	0x34, 0xaa, 0x44, 0x08, 0x56, 0xbe, 0x61, 0x11, 0x1d, 0x76, 0xf4, 0xb6, 0x5e, 0xe3, 0x87, 0xb0,
	0x56, 0x09, 0x8b, 0x54, 0x9d, 0x99, 0x11, 0x49, 0x8c, 0xa8, 0x5e, 0xa3, 0xff, 0x41, 0x97, 0x7e,
	0x2b, 0x8d, 0x98, 0x5a, 0xe2, 0xc7, 0x70, 0xe3, 0x84, 0x44, 0x6c, 0x46, 0x24, 0x4b, 0xe2, 0x66,
	0xa3, 0x4a, 0x38, 0xce, 0x4b, 0xe1, 0x38, 0xc7, 0x5b, 0x70, 0xb3, 0x2e, 0x2c, 0x52, 0x25, 0xcd,
	0x84, 0xde, 0xd3, 0xd2, 0x6e, 0x68, 0x21, 0xfe, 0xbb, 0x0b, 0xde, 0x09, 0x89, 0x32, 0x2a, 0x42,
	0x2a, 0xd0, 0x27, 0xb0, 0x42, 0xe3, 0x5c, 0x0c, 0x3b, 0x1b, 0xdd, 0xd1, 0x60, 0x7b, 0x2b, 0x68,
	0x48, 0x78, 0x50, 0x4a, 0x05, 0x7b, 0x71, 0x1e, 0x6a, 0x39, 0xff, 0xe7, 0x2e, 0x74, 0xf7, 0xe2,
	0x5c, 0x05, 0x19, 0x93, 0xb9, 0x75, 0x55, 0xaf, 0xd1, 0x73, 0x70, 0x8d, 0xcb, 0x56, 0xff, 0x76,
	0x7b, 0xfd, 0xc1, 0x51, 0x21, 0x1a, 0x96, 0x3a, 0xfc, 0x5f, 0x3b, 0xd0, 0x3f, 0xaa, 0x12, 0xff,
	0x9a, 0xbd, 0x67, 0xd0, 0x53, 0x05, 0xb0, 0xc6, 0x3e, 0x7a, 0x73, 0x63, 0xc1, 0x67, 0x2c, 0xa2,
	0x61, 0xa1, 0xc5, 0xff, 0xd3, 0x81, 0x15, 0x85, 0xaf, 0xb5, 0x75, 0x0c, 0xab, 0xb9, 0xd6, 0x60,
	0x8c, 0xed, 0xfc, 0x4b, 0x63, 0xc5, 0xa7, 0xd0, 0x28, 0xf3, 0xc7, 0xd0, 0xd3, 0x1b, 0xaa, 0xc6,
	0x17, 0xf4, 0x3b, 0x63, 0x52, 0x2d, 0xd1, 0x6d, 0xe8, 0xe9, 0x43, 0xa6, 0xee, 0x05, 0x40, 0xff,
	0x87, 0x55, 0x91, 0x64, 0x7c, 0x4a, 0x87, 0x5d, 0xbd, 0x6d, 0x10, 0xbe, 0x09, 0x6b, 0x63, 0x2a,
	0xad, 0xdd, 0x4b, 0xfc, 0x87, 0x03, 0xfd, 0xfd, 0x98, 0xe9, 0x0e, 0x79, 0x6a, 0xf3, 0xe4, 0x68,
	0xd7, 0xdf, 0x6f, 0x74, 0xdd, 0x08, 0x05, 0x47, 0x94, 0xce, 0x6a, 0xd9, 0x41, 0x3e, 0xb8, 0x99,
	0xa0, 0x5c, 0x27, 0xa6, 0xf0, 0xa8, 0xc4, 0xea, 0x5b, 0x4a, 0x84, 0xb8, 0x4a, 0xf8, 0xcc, 0xb8,
	0x55, 0x62, 0xff, 0x03, 0x70, 0xad, 0x2a, 0x7b, 0x91, 0x9d, 0xf2, 0x22, 0x97, 0xbd, 0xd2, 0xa9,
	0x7a, 0x05, 0xff, 0xee, 0x80, 0x5b, 0x78, 0x51, 0xdc, 0x6b, 0x91, 0x4d, 0xa7, 0x54, 0x08, 0x7b,
	0xaf, 0x0d, 0x54, 0x5f, 0xa2, 0xe4, 0xac, 0xd6, 0x8d, 0x16, 0xa2, 0xa7, 0xb0, 0x2a, 0x93, 0x0b,
	0x1a, 0x8b, 0x61, 0x57, 0x07, 0x7c, 0xaf, 0x45, 0xc0, 0x22, 0x0d, 0x5e, 0x28, 0x99, 0xd0, 0x88,
	0xfa, 0x0f, 0xa0, 0xa7, 0x37, 0xae, 0xbd, 0x0d, 0xd7, 0xd6, 0x06, 0x13, 0x18, 0x9c, 0x90, 0x2c,
	0x92, 0x47, 0x92, 0xc8, 0x4c, 0xa0, 0x0d, 0x18, 0xb0, 0x98, 0x49, 0x46, 0x22, 0xf6, 0x3d, 0xb5,
	0x6d, 0x59, 0xdf, 0xd2, 0xc5, 0xa4, 0x24, 0xa2, 0x33, 0xad, 0xc7, 0x0d, 0x0d, 0x52, 0xa1, 0xe5,
	0x94, 0x0b, 0x96, 0xc4, 0x26, 0x9d, 0x16, 0xe2, 0x5d, 0x70, 0x27, 0xc9, 0x19, 0xd3, 0x03, 0xa3,
	0x5e, 0x11, 0xa7, 0xa1, 0x22, 0x9d, 0xc5, 0x8a, 0xe0, 0x2f, 0xc1, 0x33, 0x3a, 0x1a, 0xf3, 0xbb,
	0x0e, 0x1e, 0xc9, 0xe4, 0xb9, 0x4e, 0x82, 0xd1, 0x51, 0x6d, 0x28, 0xd7, 0x29, 0xe7, 0x09, 0x2f,
	0x72, 0xec, 0x85, 0x06, 0xe1, 0x4d, 0xf0, 0x8e, 0x63, 0x15, 0x86, 0xf2, 0x70, 0x1d, 0xbc, 0x4c,
	0x83, 0xcf, 0xcb, 0xab, 0x5d, 0x6d, 0xe0, 0x97, 0x00, 0xf6, 0xa8, 0x48, 0x6b, 0xb9, 0x70, 0x16,
	0x72, 0xa1, 0x22, 0xe1, 0xc9, 0x19, 0x57, 0x1e, 0x2a, 0x2f, 0x7a, 0x61, 0x89, 0x95, 0x4c, 0x4c,
	0xe9, 0x8c, 0x16, 0xb7, 0xae, 0x17, 0x1a, 0x84, 0xef, 0xc0, 0xda, 0x98, 0x93, 0xf4, 0xfc, 0x70,
	0x72, 0x98, 0x51, 0xae, 0x5b, 0xe9, 0x52, 0x2d, 0x8c, 0x0f, 0x05, 0xc0, 0xbf, 0x39, 0xe0, 0x8e,
	0x0f, 0x27, 0x7b, 0xca, 0x71, 0x95, 0x87, 0x39, 0x15, 0x82, 0x9c, 0x95, 0xd3, 0xd7, 0x40, 0x34,
	0x01, 0x2f, 0x4a, 0xa6, 0x7a, 0xd2, 0xda, 0xe6, 0x0f, 0x1a, 0x2f, 0x94, 0xd5, 0x19, 0x4c, 0x8c,
	0x58, 0x58, 0x29, 0xf0, 0x1f, 0xa9, 0x02, 0x16, 0x40, 0xdd, 0xac, 0x88, 0xc5, 0x85, 0xc1, 0x5e,
	0xa8, 0xd7, 0x2a, 0xa4, 0x69, 0x12, 0x65, 0xf3, 0xd8, 0x04, 0x6b, 0x10, 0xfe, 0xd1, 0x81, 0x81,
	0x89, 0x49, 0xa7, 0xeb, 0xe3, 0x1a, 0xc9, 0x0c, 0xb6, 0xdf, 0x6d, 0x37, 0x8d, 0x0c, 0x19, 0xed,
	0x94, 0xb5, 0x2b, 0xc2, 0xb9, 0xdb, 0x2a, 0x9c, 0xb2, 0xc4, 0x3f, 0x74, 0x2a, 0xc2, 0xfb, 0x54,
	0xe9, 0x7b, 0xf6, 0xda, 0xdc, 0x7f, 0xd0, 0xa8, 0xb1, 0x2e, 0x7c, 0xcd, 0xd8, 0xff, 0xc5, 0x69,
	0x1e, 0xfb, 0x93, 0xc5, 0xb1, 0xff, 0xe8, 0x8d, 0x6d, 0x2d, 0x4c, 0xfd, 0x87, 0x0d, 0x43, 0x5f,
	0x53, 0xf2, 0x94, 0x53, 0x59, 0xd8, 0xd2, 0x94, 0xac, 0x21, 0xfe, 0xc9, 0x81, 0x5b, 0xe3, 0xc3,
	0xc9, 0x02, 0xef, 0xef, 0x2c, 0x94, 0x64, 0xb3, 0xb5, 0x5b, 0xff, 0x4d, 0x55, 0x30, 0xac, 0x1d,
	0xa7, 0x33, 0x22, 0xe9, 0x93, 0x83, 0x7d, 0xd5, 0x7b, 0x08, 0x56, 0x32, 0x1e, 0xd9, 0xb7, 0x8e,
	0x5e, 0xe3, 0x5b, 0x70, 0xa3, 0x76, 0x46, 0xa4, 0xdb, 0x7f, 0xf5, 0xe1, 0xad, 0xbd, 0x58, 0x52,
	0x9e, 0x72, 0x26, 0xa8, 0x49, 0xcf, 0x2e, 0x4f, 0x2e, 0x28, 0x47, 0xa7, 0x30, 0x18, 0x53, 0x69,
	0x1d, 0x45, 0xa3, 0x56, 0xf1, 0x84, 0xf4, 0xd2, 0xdf, 0x6c, 0x79, 0x52, 0xa4, 0x68, 0x0a, 0xae,
	0x79, 0xc7, 0x50, 0xb4, 0xf4, 0x2d, 0x52, 0xbd, 0x95, 0xfc, 0x7b, 0xad, 0xcf, 0x6a, 0x23, 0xb7,
	0xd5, 0x33, 0xd0, 0x44, 0x67, 0xed, 0x0b, 0x74, 0xa7, 0x51, 0x89, 0x79, 0x5e, 0xfa, 0x77, 0x5b,
	0x9c, 0x12, 0x29, 0xfa, 0x1a, 0xbc, 0x92, 0x7f, 0x51, 0x73, 0x06, 0xea, 0x3c, 0xed, 0xb7, 0xec,
	0x5c, 0xf4, 0x12, 0x3c, 0x45, 0x54, 0x9a, 0x5f, 0x96, 0x78, 0x6e, 0x18, 0x7c, 0x89, 0xe7, 0x25,
	0xc3, 0x7e, 0xa5, 0x3d, 0x37, 0x9c, 0xd5, 0x2c, 0x63, 0x9f, 0xdf, 0xfe, 0x68, 0x89, 0xd7, 0x15,
	0x09, 0xbe, 0x02, 0xf7, 0xc9, 0xc1, 0xbe, 0xe6, 0x9b, 0x25, 0xca, 0x2d, 0xaf, 0x2d, 0x49, 0x49,
	0x45, 0x5d, 0xaf, 0x60, 0xb5, 0xe0, 0x0f, 0xd4, 0x2c, 0x51, 0xf2, 0x91, 0xff, 0x5e, 0xab, 0x73,
	0xba, 0x9a, 0x7d, 0x33, 0x6c, 0x97, 0xd5, 0xb2, 0x46, 0x33, 0x4b, 0xb2, 0x52, 0x9f, 0xde, 0xa7,
	0xe0, 0x95, 0x8d, 0xb8, 0xc4, 0x42, 0xbd, 0xa9, 0xfd, 0xad, 0xb6, 0x47, 0x45, 0xba, 0x0b, 0x5f,
	0xb8, 0xf6, 0xcb, 0xe9, 0xaa, 0xfe, 0xbd, 0xfa, 0xf0, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70,
	0x76, 0x2c, 0xa1, 0x7c, 0x0d, 0x00, 0x00,
}
